Better Detection of Emoji in #yelling
UQComputingSociety/uqcsbot-discord pull request #157
Opened 2023-08-27 02:14 UTC by bradleysigma

Now properly detects fake emoji as yelling violations and animated emoji as non-violations.

2023-08-27 02:22 UTC, LimaoC approved these changes
yeah nah looks about right

2023-08-27 03:23 UTC, andrewj-brown requested changes
regex whinging:tm:

2023-08-27 03:23 UTC, andrewj-brown commented on uqcsbot/yelling.py
> +            r"<(?P<animated>a?):(?P<name>[a-zA-Z0-9_]{2,32}):(?P<id>[0-9]{18,22})>",
I'd prefer this to use `\w` and `\d` instead of the character classes `[a-zA-Z0-9_]` and `[0-9]`.

2023-08-30 07:49 UTC, bradleysigma commented on uqcsbot/yelling.py
> +            r"<(?P<animated>a?):(?P<name>[a-zA-Z0-9_]{2,32}):(?P<id>[0-9]{18,22})>",
I just copied the regex from an admin's message in the discordy.py server ¯\_(ツ)_/¯. Anyway, fixed.

2023-08-31 00:17 UTC, andrewj-brown reviewed
lgtm

2023-08-31 00:17 UTC, andrewj-brown approved these changes
lgtm 2 (remember to use the radio buttons this time)

2023-08-31 00:20 UTC, merged