Whatsdue: fixed to work with the new JAC system
UQComputingSociety/uqcsbot-discord pull request #207
Opened 2024-07-22 14:03 UTC by 49Indium

Recently (semester 2 2024) UQ has changed their ECP management from [ECPS](https://systems-training.its.uq.edu.au/ecps) to [JAC](https://systems-training.its.uq.edu.au/jac). This means that many of the ECP related functions stopped working (as they were based off [a old service started in 2006](https://www.courses.uq.edu.au/student_section_report.php?report=assessment&profileIds=133473)).

This PR rewrites most of these to work with the new system, letting `whatsdue` work again. There are some slight stylistic changes made to the output, due to certain links no longer being available, and the due dates for many courses actually being descriptions. ECPs from before sem 2 2024 will no longer be able to be processed, as these should no longer be needed.

There might also be some future potential to include hurdle warnings in `whatsdue`, as these are in the current ECP assessment tables, but are ignored in this PR.

Please  review harshly, as I have done a somewhat quick job at this.

2024-07-24 05:53 UTC, GoldenRedstone requested changes
All good updates beyond just fixing the critical errors. Only issues were just a few docstrings that were not updated alongside. You asked me to review harshly so I also checked your spelling.

2024-07-24 05:53 UTC, GoldenRedstone commented on uqcsbot/utils/uq_course_utils.py
>  def get_course_assessment(
Returns a list of assessment items but the name of the function and the docstring somewhat suggests that a single assessment is returned. Changing either the name or changing the docstring would be helpful but isn't required.

2024-07-24 05:53 UTC, GoldenRedstone commented on uqcsbot/whatsdue.py
>      """Provides a key to sort assessment dates by. If the date cannot be parsed, will put it with items occuring during exam block."""
Occurring is misspelled here. Other spelling mistakes include 'seperated' and 'defualts'.

2024-07-24 05:53 UTC, GoldenRedstone commented on uqcsbot/utils/uq_course_utils.py
> +    def __init__(self, course_name: str, offering: Optional[Offering] = None):
Good idea to make the error instead be for a single course.

2024-07-25 10:14 UTC, 49Indium commented
Thanks for catching all of that. I completely forgot about the doc strings.

2024-07-26 01:24 UTC, GoldenRedstone approved these changes

2024-07-27 03:51 UTC, merged