Added Cowsay
UQComputingSociety/uqcsbot-discord pull request #80
Opened 2023-04-06 23:46 UTC by lcox74

Had a weird thought, "what if `cowsay` was in discord?" Then I accidentally built that instead of doing any work.

The command is `/cowsay message`

```
 _____________ 
< hello world >
 ------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\ 
                ||----w |
                ||     ||
```

There are also optional arguments:

- `tongue` which will allow the cow to stick out its tongue
- `tux` which changes the cow to the Linux Tux
- `mood` which will change the eyes from a select list:

```py
select_list = dict(
    Normal = 'oo',
    Borg = '==',
    Dead = 'xx',
    Greed = '$$',
    Paranoid = '@@',
    Stoned = '**',
    Tired = '--',
    Wired = 'OO',
    Youthful = '..'
)
```

2023-04-07 02:24 UTC, JamesDearlove requested changes
Thanks for contributing! Hope you didn't procrastinate your work for too long. Nice one, didn't expect we'd need this, but yeah we absolutely do.

Just a couple of minor changes

2023-04-07 02:24 UTC, JamesDearlove commented on uqcsbot/cowsay.py
> +            mood: Optional[Literal['Normal', 'Borg', 'Dead', 'Greed', 'Paranoid', 'Stoned', 'Tired', 'Wired', 'Youthful']] = 'Normal',
I think as this type is used a few more times, you should have a type alias for it.

2023-04-07 02:24 UTC, JamesDearlove commented on uqcsbot/cowsay.py
> +from random import choice
Nit: Unused import

2023-04-07 02:24 UTC, JamesDearlove commented on uqcsbot/cowsay.py
> +from typing import List, NamedTuple, Optional, Union, Literal
Nit: NamedTuple and Union are also unused

2023-04-08 00:26 UTC, lcox74 commented
I amended the code to reflect the requested changes. 

Im currently out camping, writing code on your phone sucks. Also can't test to see if aliasing the Literal type works, python be pedantic.

2023-04-08 03:37 UTC, JamesDearlove approved these changes
Approved pending these final suggestions

2023-04-08 03:37 UTC, JamesDearlove commented on uqcsbot/cowsay.py
> +from typing import Optional, Literal
Missing List from typing
```suggestion
from typing import Optional, Literal, List
```

2023-04-08 03:37 UTC, JamesDearlove commented on uqcsbot/cowsay.py
> +        if len(message) == 0 or len(message) > 2000:
Cap this at 1000 characters, as its the final message it sends back that needs to be less than 2000 characters.
```suggestion
        if len(message) == 0 or len(message) > 1000:
```

2023-04-08 03:37 UTC, JamesDearlove commented on uqcsbot/cowsay.py
> +        message="The message that the cow will say",
Just making it clear that the messsage can only contain 1000 characters.

```suggestion
        message="The message that the cow will say (Max 1000 chars)",
```

2023-04-08 03:46 UTC, merged